### PR TITLE
Implement correct usage of creature_classlevelstats

### PR DESCRIPTION
**Pull request by miraco**
Care: This patch will modify creature damage, health, mana and armor. 
For health/armor/mana: All your custom creatures need to get correct exp and modifiers in creature_template 
For creature damage: As long you didnt modified min/max damage or attackpower the creature damage should be calculated just like blizzard did.

Since i cant test every creature, some creatures can get buged now. Need to change the DamageModifier manuel then.

### CODE REVIEW

**Comment by miraco** [comment]
Care: if a creature has exp -1 the server can crash

**Comment by AbraKabastard** [comment]
Any way you can add a sanity check for -1?

And I can't find where you create the template creature_classlevelstats

**Comment by miraco** [comment]
creature_classlevelstats is already in the database.

Well, there should not be a Creature with exp -1. cause if they dont have 0 or 1 they dont get health/armor/mana/damage. Thats why trinity doesnt check for that

**Comment by AbraKabastard** [comment]
Okay. I will be merging this in about 10 hours. If anyone has any ideas before then please, let us know here.

**Review by AbraKabastard — APPROVED** [review]

**Pull request merged**
