### PR TITLE
Adjusted header includes to fix building (OS: Linux, Distro:Fedora 22).

### PR DESCRIPTION
**Pull request by adeutscher**
Some missing include calls were causing me problems with building.

### CODE REVIEW

**Comment by adeutscher** [comment]
Closing this due to an error that I discovered when double-checking on another system. Will re-submit after I've corrected this error.

**Comment by adeutscher** [comment]
My error on the other system was very silly: I forgot to switch from the master branch to the dev branch. Re-opening.

**Comment by Zaffy** [comment]
Isn't this for non-pch builds?

**Comment by adeutscher** [comment]
I'm afraid I'm not familiar with using pre-compiled headers, but my `cmake` thinks that it is using them (see below).

I'm not using any switches with `cmake` that seem to involve PCH, but to confirm:

```
cmake ../ -DPREFIX=$HOME/dev/wow -Wno-dev -DTOOLS=1
```

This is the output of my `cmake` summary off of my master branch:

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found ACE library: /usr/local/lib/libACE.so
-- Found ACE headers: /usr/local/include
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so  
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib64/mysql/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found Curses library: /usr/lib64/libcurses.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found Binutils - /usr/lib64/libbfd.so, /usr/lib64/libiberty.a
-- Found Git: /usr/bin/git (found version "2.5.0") 

* OregonCore revision    : 3346 (6e0692b)
* Build binaries in      : Release mode

* Install core to        : /home/adeutscher/dev/wow/bin
* Install libraries to   : /home/adeutscher/dev/wow/lib
* Install configs to     : /home/adeutscher/dev/wow/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map extractiors  : Yes

* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Use SFMT for RNG       : No  (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Build w/ documentation : No  (default)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/adeutscher/dev/wow/src/OregonCore/build
```

**Comment by LordUsagi** [comment]
Even if it was, it wouldn't be a problem to merge.

**Pull request merged**
