### PR TITLE
(Core/Cinematic): Activate creatures and objects during opening cinematics

### PR DESCRIPTION
**Pull request by r00ty-tc**
This is a port from my same work in TrinityCore. It needed some rework of the M2 file structure (it's actually simpler in BC, for Wrath they added the ability to have multiple camera sets and then... Never used the feature.. Then again in Cata they added the chance to change the FoV during the cinematic and never used that either).

I did a cursory test, and it seemed to work. But, not extensive testing. Rerun mapextractor with -e 4 option to extract cameras, and put the Cameras folder into the same folder as dbc/maps folders.

Activate creatures and objects during opening cinematics
As well as other flyby cameras (sunwell etc)
Requires re-running map extractor to extract camera m2 files from data

As a separate commit (take or don't take) is the commit from PlayTBC that removes the lib mysql includes from the project (they need to be installed and cmake should find them). Without this change I couldn't use VS2015, so I included it. It should be a separate commit though.

### CODE REVIEW

**Comment by robinsch** [comment]
Thanks

**Comment by kotishe** [comment]
Nice!

**Comment by Zaffy** [comment]
This is cool!

About the mysqlite - it was possible to compile with VS2015 (see #1347). But anyways, it needs to be updated or removed so lets remove it then. We'll just need to improve the findmysql macro look also for mariadb stuff, once that done this can be smoothly merged.

**Comment by LordUsagi** [comment]
Fantastic!

**Comment by r00ty-tc** [comment]
Probably I'll remove the mysql commit, since it should be entirely separate (it's just a direct application of https://bitbucket.org/Caboon/playtbc_core/commits/20fd95088a8547e7ce1a15b550f6f175e25bf68a. Nothing more needed).

EDIT: Done. Plus fixed missing EOL on final line of new files.

**Pull request merged**
