### PR TITLE
Classlevel

### PR DESCRIPTION
**Pull request by miraco**
This is some work i did on a private fork in the last few months

Maybe someone is interesseted in this work an can complete it. Its currently just using the modifiers from wotlk. Afaik the formular for dmg is the same in TBC blizzard just changed the modifiers/variances for wotlk.

I didnt realy test everything ingame, but mostly the HP, Armor and melee dmg was working in ramparts.

### CODE REVIEW

**Comment by miraco** [comment]
I did some more research

I guess we first need to use 
`UPDATE creature_template SET mindmg = ROUND(`mindmg` + `attackpower` / 7) WHERE entry = xyz;
UPDATE creature_template SET maxdmg = ROUND(`maxdmg` + `attackpower` / 7) WHERE entry = xyz;`

to get mindmg and maxdmg like bestiary.

fo example
Nexus-Prince Shaffar = Unit Class 2 (BOSS)
Level 66: BaseDamage = 78.472 / Melee AttackPower = 266 / Base Melee Attack Time = 2000
Bestiary Min Dmg: 1136
Bestiary Max Dmg: 1593
Damage Variance: 1.0 (No Variance)

And to get the Damage Multiplier we need to change the forumlar from 
`CalculatedMinMeleeDmg=ROUND + (Base Melee Attackpower / 14)) * (Base Attack Time/1000)) * Damage Multiplier`
To
`Damage Multiplier = CalculatedMinMeleeDmg  /  (BaseDamage+ (Base Melee Attackpower / 14)) * (Base Attack Time/1000)) `

Should be something like this for exp0 and exp1 then
`UPDATE creature_template ct 
JOIN creature_classlevelstats cls ON ct.minlevel = cls.level AND ct.unit_class = cls.class
SET ct.DamageModifier = (ct.mindmg / (cls.basedamage_exp0 + (cls.attackpower / 14)) * (ct.BaseAttackTime / 1000)) WHERE ct.exp = "0";

UPDATE creature_template ct 
JOIN creature_classlevelstats cls ON ct.minlevel = cls.level AND ct.unit_class = cls.class
SET ct.DamageModifier = (ct.mindmg / (cls.basedamage_exp1 + (cls.attackpower / 14)) * (ct.BaseAttackTime / 1000)) WHERE ct.exp = "1";`

**Comment by AbraKabastard** [comment]
This is some nice stuff! What will we have to do to make this ready to roll out?

**Comment by miraco** [comment]
I have this rdy, just need to find it again xD Stoped working after finishing this :<

**Comment by AbraKabastard** [comment]
Okay. If you need any help, let me know. I'd love to see the PR when you're ready!

**Pull request closed without merging**
