### PR TITLE
[Core/DB] Fix base db structure

### PR DESCRIPTION
**Pull request by ghost**
It would give you an error when you tried to apply the sql

### CODE REVIEW

**Comment by DkVagabonden** [comment]
Great to see people working on this!

**Comment by kotishe** [comment]
Good. But need more changes, where @Selphius and he 300+ db commits?

**Comment by Selphius** [comment]
@kotishe 
Far, far away xD

I stopped fixing stuff etc. for WoW, I gave everything I had regarding my DB to Zaffy if I remember correctly. Though it was entire DB not commits for all those commits I made (it is old one too, lacks SAI)

**Comment by kotishe** [comment]
Sad, need moar db dev
=(

**Comment by LordUsagi** [comment]
I Approve

**Pull request merged**
