### PR TITLE
[WIP][CMake] Cleaned up, Optimize CMake & Upgrade

### PR DESCRIPTION
**Pull request by Meltie2013**
# Updating CMake to 3.0
- Uses inherited dependencies & awesome new features as described in [this guide](https://rix0r.nl/blog/2015/08/13/cmake-guide/)!
- Removes some work arounds which target lower CMake Versions
- Automatic inclusion now which makes it easier to add new sources, etc.

**Target Branch**: master

**Issues Addressed**:
- Lot of dependency clutter in whole cmake build files -> proper usage of libraries not utilized.
- Difficult "possible future linking to shared libraries" -> this patch makes it much easier through the
  usage of CMakes internal "BUILD_SHARE_LIBS" option.
- Circular dependency between all areas, the dependency graph is direct acyclic now.

**Upgrades to do**:
- [ ] Upgrade CMake to 3.0 (minimum)
- [ ] Apply required upgrades

**Make sure this stays as a WIP, if merged to early, it will cause issues building**
**Notice: This is a port from my project "FireStorm"**.

### CODE REVIEW

**Comment by Zaffy** [comment]
Hello! Thanks for sharing but...
- as you can see automatic build failed due to lack of checking whether a policy exists. For example the policy CMP0005 was introduced in cmake 3.5.2 and is unknown to previous versions, also when a policy is not set its automatically set to be the old behavior.
- there's no sense replacing the if NOT CMAKE_BUILD_TYPE condition, it's mostly for linux systems so they are able to build in debug mode just by allowing `WITH_COREDEBUG`
- a lot of todos doesn't really solve anything... perhpas you just chose wrong branch or so?

**Comment by Meltie2013** [comment]
Its incomplete right now. Why it said in the notes, that it wouldn't build. Once more is done with the PR, it will work. WIPs normally wont build in Travis anyways.

**Comment by LordUsagi** [comment]
Actually NO pull requests build in Travis. We've got it set not to test PRs

**Comment by Zaffy** [comment]
@LordUsagi  this is not true. PRs do get tested by travis.

**Comment by kotishe** [comment]
@Zaffy yes, test PRs in my fork =p

**Comment by Meltie2013** [comment]
@Zaffy Only time PRs are tested, is when they're finished. Its intended by most users that place up PRs, do to unfinished work.

**Comment by LordUsagi** [comment]
I look forward to this one!

**Comment by Meltie2013** [comment]
@LordUsagi You should like it once its done. Never have to worry about forgetting to add a file into CMakeLists.txt again. It will automatically find the file/source, after a rerun of CMake. Since its going to be a while do to rewriting files.

**Comment by LordUsagi** [comment]
@Sylica2013 Hows this one going?

**Comment by Meltie2013** [comment]
@LordUsagi Bad, haven't got the chance to work on anything lately. This one is having issues with CMake, do to the major changes in the CMake files. For now, this will be closed till I can finish it up.

**Pull request closed without merging**
