### PR TITLE
Fix Cmake Policy CMP0059 Warning

### PR DESCRIPTION
**Pull request by kotishe**

### CODE REVIEW

**Comment by AbraKabastard** [comment]
Why does this warning happen?

**Comment by kotishe** [comment]
If use CMake version > 3.x 
Have this

CMake Warning (dev) at cmake/macros/FindPCHSupport.cmake:65 (GET_DIRECTORY_PROPE                                                                                                                                                                                                                                             RTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  cmake/macros/FindPCHSupport.cmake:218 (_PCH_GET_COMPILE_FLAGS)
  src/game/CMakeLists.txt:57 (add_precompiled_header)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/macros/FindPCHSupport.cmake:66 (GET_DIRECTORY_PROPE                                                                                                                                                                                                                                             RTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  cmake/macros/FindPCHSupport.cmake:218 (_PCH_GET_COMPILE_FLAGS)
  src/game/CMakeLists.txt:57 (add_precompiled_header)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/macros/FindPCHSupport.cmake:65 (GET_DIRECTORY_PROPE                                                                                                                                                                                                                                             RTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  cmake/macros/FindPCHSupport.cmake:218 (_PCH_GET_COMPILE_FLAGS)
  src/scripts/CMakeLists.txt:79 (add_precompiled_header)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/macros/FindPCHSupport.cmake:66 (GET_DIRECTORY_PROPE                                                                                                                                                                                                                                             RTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  cmake/macros/FindPCHSupport.cmake:218 (_PCH_GET_COMPILE_FLAGS)
  src/scripts/CMakeLists.txt:79 (add_precompiled_header)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by kotishe** [comment]
Also now VS don't compile

**Comment by AbraKabastard** [comment]
Lmao. Gotta find a way to make both work

**Pull request merged**
