### PR TITLE
Updated World.Sql

### PR DESCRIPTION
**Pull request by yvoms**
Fixed a minor issue, where the verision table was not created.

### CODE REVIEW

**Comment by Zaffy** [comment]
I think the table was omitted on purpose, why do you need it?

**Comment by yvoms** [comment]
Because the worldserver requires it, compiled on the latest revision yet it asks for this table.

**Comment by Zaffy** [comment]
Can i ask where exactly? I remember there was a startup error but only because it should have been removed/updated too. Version is taken from git and db version is taken from updates table.

**Comment by zgn1988** [comment]
make a request to the desired location + update the database

**Comment by LordUsagi** [comment]
yes can confirm this is not needed, the core does it

**Comment by zgn1988** [comment]
https://github.com/OregonCore/OregonCore/releases/tag/BaseDatabaseFull

https://github.com/OregonCore/OregonCore/blob/master/sql/updates/world/2016_11_12_00.sql

okey?

**Comment by LordUsagi** [comment]
seems okay

**Pull request closed without merging**
