### PR TITLE
Core/Script boss_amnennar_the_coldbringer.cpp

### PR DESCRIPTION
**Pull request by talamortis**
Pre nerf for boss amnennar the coldbringer, should spawn 3 waves of mobs instead of 2 waves

### CODE REVIEW

**Comment by Lumber-Jack-2** [comment]
source http://wowwiki.wikia.com/wiki/Amnennar_the_Coldbringer

**Comment by talamortis** [comment]
http://wowwiki.wikia.com/wiki/Amnennar_the_Coldbringer#Strategy

**Comment by talamortis** [comment]
@Rushor is this repo still working? or is it dead i see last update was 17 days ago?

**Comment by Lumber-Jack-2** [comment]
infos on this can be found here https://github.com/OregonCore/OregonCore/issues/1508

**Comment by zgn1988** [comment]
talamortis, your nickname on bitbucket?

**Comment by talamortis** [comment]
talamortis1, why whats up?

**Comment by zgn1988** [comment]
https://bitbucket.org/zgn/projecttbc/commits/all I have opened access

**Comment by talamortis** [comment]
thanks @Zaffy

**Pull request merged**
